plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/krishna/Library/CloudStorage/GoogleDrive-adi36k@gmail.com/My Drive/Projects-Dome/000.CV/arabiangrid-site"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]